In [2]:
import edfg_cube_api as eca
import polars as pl
from great_tables import GT, md, style, loc
from dotenv import load_dotenv

load_dotenv()

True

In [ ]:
# Recupere les VB associees a chaque fonds de la poche Europe, par isin

df=eca.cube_table(["VB"],
                  by=['isin'],
                  date="2026-04-17",
                  niv5="Europe")

print(df)

2026-04-23 15:30:47.362 | DEBUG    | edfg_cube_api._cache:cache_get:80 - cache miss: fd1211f68c49

shape: (20, 2)
┌──────────────┬───────────────┐
│ ISIN         ┆ VB            │
│ ---          ┆ ---           │
│ str          ┆ f64           │
╞══════════════╪═══════════════╡
│ null         ┆ 309748.717682 │
│ FR0013256617 ┆ 2.8157e7      │
│ FR0013289535 ┆ 9.8866e7      │
│ FR0013406998 ┆ 3.8148e7      │
│ FR0013536489 ┆ 3.04304e7     │
│ …            ┆ …             │
│ LU1443248544 ┆ 9.4378e7      │
│ LU1681042518 ┆ 6.0455e7      │
│ LU1737652310 ┆ 4.6197e8      │
│ LU1797811236 ┆ 1.1059e8      │
│ LU2403885960 ┆ 7.3752e7      │
└──────────────┴───────────────┘

In [ ]:
# Recupere les VB associees a chaque fonds et trace le tableau, avec le nom de l'instrument a la place de l' isin

df=eca.cube_table(["Performance VL YTD INS %","VB"],
                  by=['instrument'],
                  date="2026-04-17",
                  niv5="Europe")

df = df.with_columns((pl.col("VB") / pl.col("VB").sum()).alias("Poids"))

df = df.rename({
    "Instrument": "Fonds",
    "VB": "Valorisation",
    "Performance VL YTD INS %": "Perf 2026"
})

df=df.filter(pl.col("Fonds")!="None")

tableau = (
    GT(df).tab_header(
        title =md('Poche Europe'),
        subtitle =md("Valorisation du 17-04-2026")
    )
    .fmt_currency(columns=['Valorisation'],compact=6,currency="EUR",decimals=0)
    .fmt_percent(columns=["Perf 2026","Poids"],decimals=1)
    .tab_source_note(source_note=md("Comgest Compounders sorti totalement du portefeuille depuis le 20/04"))
    # .tab_style(
    #     style=style.fill(color="cyan"),
    #     locations=loc.body(columns="Fonds"))
)

tableau.opt_stylize(style=6,color="blue")

2026-04-22 15:05:34.999 | DEBUG    | edfg_cube_api._cache:cache_get:83 - cache hit: 021e670b80da

GT(_tbl_data=shape: (19, 4)
┌─────────────────────────────────┬───────────┬──────────────┬──────────┐
│ Fonds                           ┆ Perf 2026 ┆ Valorisation ┆ Poids    │
│ ---                             ┆ ---       ┆ ---          ┆ ---      │
│ str                             ┆ f64       ┆ f64          ┆ f64      │
╞═════════════════════════════════╪═══════════╪══════════════╪══════════╡
│ BDL EUROPE CONVICTIONS - I - E… ┆ 0.069201  ┆ 9.8866e7     ┆ 0.040252 │
│ COMGEST EUROPE COMP EUR EA ACC  ┆ -0.044747 ┆ 5.1588e7     ┆ 0.021003 │
│ DNCA ARCHER MID CAP EUROPE SI … ┆ 0.042777  ┆ 7.3752e7     ┆ 0.030027 │
│ ECHIQ AGENOR IXL EUR NH         ┆ 0.082002  ┆ 3.8148e7     ┆ 0.015531 │
│ ELEVA EUROPEAN SEL I EUR ACC U… ┆ null      ┆ 1.2590e8     ┆ 0.051257 │
│ …                               ┆ …         ┆ …            ┆ …        │
│ M&G EUROPEAN STGIC VALUE EUR C… ┆ 0.062733  ┆ 1.1059e8     ┆ 0.045024 │
│ STAR PASTEUR CHF                ┆ 0.053662  ┆ 1.3475e8     ┆ 0.054862 │
│ STAR PASTEUR GBP                ┆ 0.062341  ┆ 3.0517e8     ┆ 0.124247 │
│ SYCOMORE OBJ CLIM ACTIONS 2 NH… ┆ 0.124877  ┆ 3.04304e7    ┆ 0.012389 │
│ VANGUARD EUROPEAN STOCK IDX I … ┆ 0.065443  ┆ 2.2163e8     ┆ 0.090234 │
└─────────────────────────────────┴───────────┴──────────────┴──────────┘, _body=<great_tables._gt_data.Body object at 0x000002553494AC90>, _boxhead=Boxhead([ColInfo(var='Fonds', type=<ColInfoTypeEnum.default: 1>, column_label='Fonds', column_align='left', column_width=None), ColInfo(var='Perf 2026', type=<ColInfoTypeEnum.default: 1>, column_label='Perf 2026', column_align='right', column_width=None), ColInfo(var='Valorisation', type=<ColInfoTypeEnum.default: 1>, column_label='Valorisation', column_align='right', column_width=None), ColInfo(var='Poids', type=<ColInfoTypeEnum.default: 1>, column_label='Poids', column_align='right', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x0000025534751A30>, _spanners=Spanners([]), _heading=Heading(title=Md(text='Poche Europe'), subtitle=Md(text='Valorisation du 17-04-2026'), preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x00000255348F28A0>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x00000255348F2B70>, _source_notes=[Md(text='Comgest Compounders sorti totalement du portefeuille depuis le 20/04')], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x00000255347528D0>, _formats=[<great_tables._gt_data.FormatInfo object at 0x00000255348F2D50>, <great_tables._gt_data.FormatInfo object at 0x00000255348F2C60>], _substitutions=[], _col_merge=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#5F5F5F'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#5F5F5F'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#5F5F5F'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#0076BA'), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#5F5F5F'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#5F5F5F'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#5F5F5F'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#5F5F5F'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D5D5D5'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D5D5D5'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#5F5F5F'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#5F5F5F'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value='#89D3FE'), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D5D5D5'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D5D5D5'), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#EDF7FC'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=['True']), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

In [6]:
eca.list_values("niv5")

2026-04-22 11:06:46.771 | DEBUG    | edfg_cube_api._cache:cache_get:80 - cache miss: 75cdf4c7da41

['Portefeuille principal',
 'Portfeuille financier',
 'Actions',
 'Amérique du Nord',
 'Europe',
 'Japon',
 'Bassin Pacifique',
 'Pays Emergents',
 'Obligations convertibles',
 'Actions Monde',
 'Liquidités Actions',
 'Obligations',
 'Obligations souveraines',
 'Souverains DMF',
 'Indexées inflation',
 'Obligations crédit corporate',
 'Crédit DMF',
 'Crédit HY Court terme',
 'Crédit OPCVM',
 'Gestion Flexible',
 'Liquidités Obligations',
 'Actifs sans risques',
 'Trésorerie OPCVM',
 'Liquidités Trésorerie',
 'Portefeuille Fonds Diversifiés de dette privée',
 "Co-Entreprise de Transport d'Electricité",
 "Actifs d'infrastucture hors CTE",
 'Actifs immobiliers',
 "Fonds d'infrastructure",
 "Fonds d'immobilier",
 'Fonds de croissance',
 'Fonds de dette à haut rendement',
 'Fonds de dette senior (ex "fonds de dette diversifiés")',
 None]

# Attribution de performance relative 2025 — Poche Europe

Méthodologie :

1. Récupère la VB de chaque fonds par ISIN à chaque **date VL** de 2025 (+ dernière VL 2024 pour la borne initiale).
2. Récupère l'historique quotidien de `TOT_RETURN_INDEX_GROSS_DVDS` sur Bloomberg pour chaque fonds (via son `Code Bloomberg`) et pour le benchmark `M7EU Index`.
3. Pour chaque période `[t-1, t]` entre deux dates VL :
   - poids de début de période `w_i,t = VB_i,t-1 / Σ VB_j,t-1`
   - retour du fonds `r_i,t = TRI_t / TRI_{t-1} - 1`
   - retour portefeuille `r_p,t = Σ_i w_i,t · r_i,t`
   - retour benchmark `r_b,t`
4. Chaînage annuel : `R_P = Π(1+r_p,t) - 1`, idem `R_B`.
5. Attribution relative avec **lissage de Carino** :
   - `k_t = (ln(1+r_p,t) − ln(1+r_b,t)) / (r_p,t − r_b,t)`, `K` idem au niveau annuel
   - contribution du fonds `i` : `C_i = Σ_t (k_t/K) · w_i,t · (r_i,t − r_b,t)`
   - garantie : `Σ_i C_i = R_P − R_B`

In [83]:
from edfg_bloomany_api import configure as configure_bloom
from edfg_bloomany_api import get_historical
from edfg_cube_api import configure as configure_cube
import numpy as np

configure_cube(cache_enabled=True)
configure_bloom(cache_enabled=True)

POCHE = "Europe"
BENCHMARK = "M7EU Index"
BLOOM_FIELD = "TOT_RETURN_INDEX_GROSS_DVDS"  # bascule vers "PX_LAST" si besoin
START = "2024-12-01"
END = "2025-12-31"

In [84]:
# VB par (date VL, ISIN) pour la poche Europe
# On inclut decembre 2024 pour avoir la derniere VL 2024 = borne initiale du 1er retour 2025

df_vb = (
    eca.cube_table(
        "VB",
        by=["date", "isin"],
        date=(START, END),
        filters={"D_Calendrier[Date VL (Y/N)]": "Y"},
        niv5=POCHE,
    )
    .filter(pl.col("ISIN").is_not_null())
)

print("Dates VL:", sorted(df_vb["Date"].unique().to_list()))
print("Nb ISINs:", df_vb["ISIN"].n_unique())
df_vb

# En cas de filtre vide, decommenter pour verifier les valeurs du flag:
# eca.list_values("D_Calendrier[Date VL (Y/N)]")

2026-04-23 20:22:30.255 | DEBUG    | edfg_cube_api._cache:cache_get:83 - cache hit: 0893dff38dd8

Dates VL: ['2024-12-06T00:00:00', '2024-12-13T00:00:00', '2024-12-20T00:00:00', '2024-12-27T00:00:00', '2024-12-31T00:00:00', '2025-01-03T00:00:00', '2025-01-10T00:00:00', '2025-01-17T00:00:00', '2025-01-24T00:00:00', '2025-01-31T00:00:00', '2025-02-07T00:00:00', '2025-02-14T00:00:00', '2025-02-21T00:00:00', '2025-02-28T00:00:00', '2025-03-07T00:00:00', '2025-03-14T00:00:00', '2025-03-21T00:00:00', '2025-03-28T00:00:00', '2025-03-31T00:00:00', '2025-04-04T00:00:00', '2025-04-11T00:00:00', '2025-04-17T00:00:00', '2025-04-25T00:00:00', '2025-04-30T00:00:00', '2025-05-09T00:00:00', '2025-05-16T00:00:00', '2025-05-23T00:00:00', '2025-05-30T00:00:00', '2025-06-06T00:00:00', '2025-06-13T00:00:00', '2025-06-20T00:00:00', '2025-06-30T00:00:00', '2025-07-04T00:00:00', '2025-07-11T00:00:00', '2025-07-18T00:00:00', '2025-07-25T00:00:00', '2025-07-31T00:00:00', '2025-08-08T00:00:00', '2025-08-14T00:00:00', '2025-08-22T00:00:00', '2025-08-29T00:00:00', '2025-09-05T00:00:00', '2025-09-12T00:00:00', '2025-09-19T00:00:00', '2025-09-26T00:00:00', '2025-09-30T00:00:00', '2025-10-03T00:00:00', '2025-10-10T00:00:00', '2025-10-17T00:00:00', '2025-10-24T00:00:00', '2025-10-31T00:00:00', '2025-11-07T00:00:00', '2025-11-14T00:00:00', '2025-11-21T00:00:00', '2025-11-28T00:00:00', '2025-12-05T00:00:00', '2025-12-12T00:00:00', '2025-12-19T00:00:00', '2025-12-24T00:00:00', '2025-12-31T00:00:00']
Nb ISINs: 29

shape: (1_562, 3)
┌─────────────────────┬──────────────┬───────────────┐
│ Date                ┆ ISIN         ┆ VB            │
│ ---                 ┆ ---          ┆ ---           │
│ str                 ┆ str          ┆ f64           │
╞═════════════════════╪══════════════╪═══════════════╡
│ 2024-12-06T00:00:00 ┆ FR0010201897 ┆ 4.6697e7      │
│ 2024-12-06T00:00:00 ┆ FR0010251108 ┆ 3.7993e7      │
│ 2024-12-06T00:00:00 ┆ FR0011742683 ┆ 183433.838809 │
│ 2024-12-06T00:00:00 ┆ FR0013256617 ┆ 3.6969e7      │
│ 2024-12-06T00:00:00 ┆ FR0013289535 ┆ 6.0299e7      │
│ …                   ┆ …            ┆ …             │
│ 2025-12-31T00:00:00 ┆ LU1443248544 ┆ 9.1751e7      │
│ 2025-12-31T00:00:00 ┆ LU1681042518 ┆ 5.6271e7      │
│ 2025-12-31T00:00:00 ┆ LU1737652310 ┆ 3.1998e8      │
│ 2025-12-31T00:00:00 ┆ LU1797811236 ┆ 1.0406e8      │
│ 2025-12-31T00:00:00 ┆ LU2403885960 ┆ 7.0726e7      │
└─────────────────────┴──────────────┴───────────────┘

In [85]:
# Mapping ISIN -> Code Bloomberg + Instrument (pour nommage final)

df_meta = (
    eca.cube_table(
        "VB",
        by=["isin", "instrument", "code_bloomberg"],
        date=(START, END),
        filters={"D_Calendrier[Date VL (Y/N)]": "Y"},
        niv5=POCHE,
    )
    .filter(pl.col("ISIN").is_not_null())
    .unique(subset=["ISIN"])
    .select(["ISIN", "Instrument", "Code Bloomberg"])
)

df_meta

2026-04-23 20:22:35.179 | DEBUG    | edfg_cube_api._cache:cache_get:83 - cache hit: ce3aac24e5de

shape: (29, 3)
┌──────────────┬─────────────────────────────────┬───────────────────┐
│ ISIN         ┆ Instrument                      ┆ Code Bloomberg    │
│ ---          ┆ ---                             ┆ ---               │
│ str          ┆ str                             ┆ str               │
╞══════════════╪═════════════════════════════════╪═══════════════════╡
│ FR0010201897 ┆ AXA AEDIFICANDI                 ┆ AXAEDII FP        │
│ FR0010251108 ┆ ODDO AVENIR EUROPE CI EUR       ┆ ODEUMCB FP        │
│ FR0011742683 ┆ EMERGENCE ACTIONS               ┆ EMGACTD FP        │
│ FR0013256617 ┆ EMERGENCE ACT 2                 ┆ EMAIIDC FP        │
│ FR0013289535 ┆ BDL EUROPE CONVICTIONS - I - E… ┆ BDLCONI FP        │
│ …            ┆ …                               ┆ …                 │
│ LU1681042518 ┆ ETF AMUNDI MSCI EUROPE VALUE F… ┆ CV9 FP            │
│ LU1681042609 ┆ ETF AMUNDI MSCI EUROPE - GBP -… ┆ CEUR LN           │
│ LU1737652310 ┆ ETF AMUNDI MSCI EUROPE - GBP D  ┆ CE2D LN           │
│ LU1797811236 ┆ M&G EUROPEAN STGIC VALUE EUR C… ┆ MGSECIA LX        │
│ LU2403885960 ┆ DNCA ARCHER MID CAP EUROPE SI … ┆ DNAMESE LX Equity │
└──────────────┴─────────────────────────────────┴───────────────────┘

In [87]:
# Benchmarks de style disponibles pour les fonds
STYLE_BENCHMARKS = [
    "M7EU Index",       # Broad (default)
    "M7EU000G Index",   # Growth
    "M7EU000V Index",   # Value
    "M7EUSM Index",     # Small / Mid
]

# Mapping manuel : nom d'instrument (colonne Instrument) -> ticker du benchmark de style
# Tout fonds absent du dict tombe sur BENCHMARK (M7EU Index) par defaut
FUND_BENCHMARK: dict[str, str] = {
    # "Nom exact de l'instrument": "M7EU000G Index",
    "ARBEVEL PLUVALCA DISRUPT OPP SI EUR": "M7EUSM Index",
    "AXA AEDIFICANDI": "M7EU000V Index",
    "COMGEST EUROPE COMP EUR EA ACC": "M7EU000G Index",
    "COMGEST GROWTH EUROPE EUR I ACC": "M7EU000G Index",
    "DNCA ARCHER MID CAP EUROPE SI - EUR": "M7EUSM Index",
    "ECHIQ AGENOR IXL EUR NH": "M7EUSM Index",
    "ETF AMUNDI MSCI EUROPE VALUE FACTOR": "M7EU000V Index",
    "ETF ISHARES EUROPE VALUE FACTOR": "M7EU000V Index",
    "ING(L) INVEST EURO HIGH DIV I": "M7EU000V Index",
    "M&G EUROPEAN STGIC VALUE EUR CI ACC": "M7EU000V Index",
    "MANDARINE EUROPE MICROCAP M EUR NH": "M7EUSM Index",
    "ODDO AVENIR EUROPE CI EUR": "M7EUSM Index"
}

# Apercu des fonds a mapper (edite FUND_BENCHMARK puis relance cette cellule)
print("Fonds -> benchmark de style (defaut = M7EU Index) :")
for inst in sorted(df_meta["Instrument"].unique().to_list()):
    print(f"  {inst:50s} -> {FUND_BENCHMARK.get(inst, BENCHMARK)}")

Fonds -> benchmark de style (defaut = M7EU Index) :
  ARBEVEL PLUVALCA DISRUPT OPP SI EUR                -> M7EUSM Index
  AXA AEDIFICANDI                                    -> M7EU000V Index
  BDL EUROPE CONVICTIONS - I - EUR                   -> M7EU Index
  COMGEST EUROPE COMP EUR EA ACC                     -> M7EU000G Index
  COMGEST GROWTH EUROPE EUR I ACC                    -> M7EU000G Index
  DNCA ARCHER MID CAP EUROPE SI - EUR                -> M7EUSM Index
  ECHIQ AGENOR IXL EUR NH                            -> M7EUSM Index
  EMERGENCE ACT 2                                    -> M7EU Index
  EMERGENCE ACTIONS                                  -> M7EU Index
  EMERGENCE EUROPE                                   -> M7EU Index
  ETF AMUNDI MSCI EUROPE - GBP - C                   -> M7EU Index
  ETF AMUNDI MSCI EUROPE - GBP D                     -> M7EU Index
  ETF AMUNDI MSCI EUROPE VALUE FACTOR                -> M7EU000V Index
  ETF ISHARES CORE FTSE 100 UCITS GBP                -> M7EU Index
  ETF ISHARES CORE MSCI EUROPE GBP                   -> M7EU Index
  ETF ISHARES EUROPE VALUE FACTOR                    -> M7EU000V Index
  ETF ISHARES MSCI EUROPE CS NH EUR                  -> M7EU Index
  ETF ISHARES MSCI EUROPE HC NH EUR                  -> M7EU Index
  ETF SPDR MSCI EUROP FINANC UCITS                   -> M7EU Index
  EXANE EQ SEL EUROPE S                              -> M7EU Index
  ING(L) INVEST EURO HIGH DIV I                      -> M7EU000V Index
  M&G EUROPEAN STGIC VALUE EUR CI ACC                -> M7EU000V Index
  MANDARINE EUROPE MICROCAP M EUR NH                 -> M7EUSM Index
  ODDO AVENIR EUROPE CI EUR                          -> M7EUSM Index
  STAR PASTEUR                                       -> M7EU Index
  STAR PASTEUR CHF                                   -> M7EU Index
  STAR PASTEUR GBP                                   -> M7EU Index
  SYCOMORE OBJ CLIM ACTIONS 2 NH EURO                -> M7EU Index
  VANGUARD EUROPEAN STOCK IDX I FUND                 -> M7EU Index

In [88]:
# Historique Bloomberg quotidien pour tous les fonds + les benchmarks, force en EUR via BQL

from edfg_bloomany_api import get_bql

YELLOW_KEYS = (
    "Equity",
    "Index",
    "Govt",
    "Corp",
    "Curncy",
    "Comdty",
    "Mtge",
    "Muni",
    "Pfd",
)


def normalize_ticker(t: str) -> str:
    if t is None:
        return t
    parts = t.strip().split()
    if parts and parts[-1] in YELLOW_KEYS:
        return " ".join(parts)
    return f"{t.strip()} Equity"


df_meta = df_meta.with_columns(
    pl.col("Code Bloomberg")
    .map_elements(normalize_ticker, return_dtype=pl.Utf8)
    .alias("Code Bloomberg")
)

tickers = df_meta["Code Bloomberg"].drop_nulls().unique().to_list()
all_secs = sorted(set(tickers) | set(STYLE_BENCHMARKS))

bql_field = BLOOM_FIELD.lower()
tickers_str = ", ".join(f"'{t}'" for t in all_secs)

expr = f"""
let(#tri = {bql_field}(currency=EUR);)
get(#tri)
for([{tickers_str}])
with(dates=range({START}, {END}), fill=PREV)
"""

results = get_bql(expr)
df0 = results[0]
tri_col = next(c for c in df0.columns if c not in ("ID", "DATE", "CURRENCY"))

df_bloom = (
    df0.rename({"ID": "Code Bloomberg", "DATE": "Date", tri_col: "TRI"})
    .select(["Code Bloomberg", "Date", "TRI"])
)

missing = set(all_secs) - set(df_bloom["Code Bloomberg"].unique().to_list())
print(
    f"Securities recuperees (BQL, EUR): {df_bloom['Code Bloomberg'].n_unique()} / "
    f"{len(all_secs)}"
)
if missing:
    print(f"Manquantes: {missing}")

df_bloom.head()

2026-04-23 20:27:55.360 | DEBUG    | edfg_bloomany_api._cache:cache_get:86 - cache miss: bql a0df26b6664c

Securities recuperees (BQL, EUR): 33 / 33
Manquantes: {' Equity'}

shape: (5, 3)
┌───────────────────┬────────────┬────────┐
│ Code Bloomberg    ┆ Date       ┆ TRI    │
│ ---               ┆ ---        ┆ ---    │
│ str               ┆ date       ┆ f64    │
╞═══════════════════╪════════════╪════════╡
│ Equity            ┆ null       ┆ null   │
│ AXAEDII FP Equity ┆ 2024-12-01 ┆ 602.55 │
│ AXAEDII FP Equity ┆ 2024-12-02 ┆ 593.91 │
│ AXAEDII FP Equity ┆ 2024-12-03 ┆ 592.39 │
│ AXAEDII FP Equity ┆ 2024-12-04 ┆ 599.46 │
└───────────────────┴────────────┴────────┘

In [89]:
# Echantillonne les series Bloomberg aux dates VL (ffill si pas de quote le jour exact)
# Le cube renvoie les dates sous forme "2024-12-06T00:00:00" : on parse en Datetime puis on caste en Date

df_vb = df_vb.with_columns(
    pl.col("Date").str.to_datetime(strict=False).dt.date().alias("Date")
).drop_nulls("Date")

vl_dates = sorted(df_vb["Date"].unique().drop_nulls().to_list())

df_wide = (
    df_bloom.with_columns(pl.col("Date").cast(pl.Date, strict=False))
    .drop_nulls("Date")
    .pivot(values="TRI", index="Date", on="Code Bloomberg")
    .sort("Date")
)

bloom_dates = df_wide["Date"].drop_nulls().to_list()
all_dates = sorted(set(bloom_dates) | set(vl_dates))

df_tri_at_vl = (
    pl.DataFrame({"Date": all_dates}).sort("Date")
    .join(df_wide, on="Date", how="left")
    .fill_null(strategy="forward")
    .filter(pl.col("Date").is_in(vl_dates))
)

print(f"Dates VL retenues: {df_tri_at_vl.height}  (attendu: {len(vl_dates)})")
df_tri_at_vl

Dates VL retenues: 60  (attendu: 60)

shape: (60, 33)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Date      ┆ AXAEDII   ┆ BDLCONI   ┆ CE2D LN   ┆ … ┆ STRPSCD   ┆ STSPCCC   ┆ STZ FP    ┆ VANEINI  │
│ ---       ┆ FP Equity ┆ FP Equity ┆ Equity    ┆   ┆ FP Equity ┆ FP Equity ┆ Equity    ┆ ID       │
│ date      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ Equity   │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024-12-0 ┆ 597.41    ┆ 1449.43   ┆ 67.126809 ┆ … ┆ 1449.6958 ┆ 1136.9171 ┆ 93.7552   ┆ 32.5724  │
│ 6         ┆           ┆           ┆           ┆   ┆           ┆ 49        ┆           ┆          │
│ 2024-12-1 ┆ 581.35    ┆ 1441.23   ┆ 66.617881 ┆ … ┆ 1438.972  ┆ 1129.5949 ┆ 93.791    ┆ 32.3252  │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆ 48        ┆           ┆          │
│ 2024-12-2 ┆ 563.38    ┆ 1377.85   ┆ 64.905351 ┆ … ┆ 1399.0659 ┆ 1097.2559 ┆ 91.3673   ┆ 31.43    │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆ 72        ┆           ┆          │
│ 2024-12-2 ┆ 566.74    ┆ 1392.34   ┆ 65.327361 ┆ … ┆ 1413.2438 ┆ 1107.5316 ┆ 92.442    ┆ 31.8091  │
│ 7         ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆          │
│ 2024-12-3 ┆ 567.79    ┆ 1397.15   ┆ 65.486333 ┆ … ┆ 1414.4234 ┆ 1108.5340 ┆ 92.883    ┆ 31.7713  │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ 18        ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-12-0 ┆ 613.2     ┆ 1722.1    ┆ 76.601669 ┆ … ┆ 1648.1102 ┆ 1292.6077 ┆ 128.0047  ┆ 37.1985  │
│ 5         ┆           ┆           ┆           ┆   ┆           ┆ 38        ┆           ┆          │
│ 2025-12-1 ┆ 599.91    ┆ 1725.88   ┆ 76.600019 ┆ … ┆ 1646.3979 ┆ 1291.4337 ┆ 130.1079  ┆ 37.1576  │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆ 67        ┆           ┆          │
│ 2025-12-1 ┆ 607.38    ┆ 1736.63   ┆ 77.785426 ┆ … ┆ 1672.2166 ┆ 1312.2597 ┆ 135.1557  ┆ 37.8228  │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆ 95        ┆           ┆          │
│ 2025-12-2 ┆ 608.06    ┆ 1726.52   ┆ 77.855869 ┆ … ┆ 1675.2091 ┆ 1315.1201 ┆ 135.7437  ┆ 37.8081  │
│ 4         ┆           ┆           ┆           ┆   ┆           ┆ 45        ┆           ┆          │
│ 2025-12-3 ┆ 616.97    ┆ 1742.17   ┆ 78.416666 ┆ … ┆ 1685.0422 ┆ 1321.0130 ┆ 136.3502  ┆ 38.03    │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ 32        ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [90]:
# Retours entre deux dates VL consecutives : r = TRI_t / TRI_{t-1} - 1
# On ne garde que les periodes dont la *fin* tombe en 2025 :
# la 1ere periode retenue est donc [derniere VL 2024 -> 1ere VL 2025]

import datetime as dt

YEAR = 2025

df_tri_long = (
    df_tri_at_vl.unpivot(index="Date", variable_name="Code Bloomberg", value_name="TRI")
    .sort(["Code Bloomberg", "Date"])
)

df_ret = (
    df_tri_long.with_columns(
        [
            (pl.col("TRI") / pl.col("TRI").shift(1).over("Code Bloomberg") - 1).alias("r"),
            pl.col("Date").shift(1).over("Code Bloomberg").alias("prev_date"),
        ]
    )
    .drop_nulls("r")
    .filter(pl.col("Date") >= dt.date(YEAR, 1, 1))
    .filter(pl.col("Date") <= dt.date(YEAR, 12, 31))
)

print(f"Periodes retenues: de {df_ret['prev_date'].min()} a {df_ret['Date'].max()}")
df_ret

Periodes retenues: de 2024-12-31 a 2025-12-31

shape: (1_705, 5)
┌────────────┬───────────────────┬─────────┬───────────┬────────────┐
│ Date       ┆ Code Bloomberg    ┆ TRI     ┆ r         ┆ prev_date  │
│ ---        ┆ ---               ┆ ---     ┆ ---       ┆ ---        │
│ date       ┆ str               ┆ f64     ┆ f64       ┆ date       │
╞════════════╪═══════════════════╪═════════╪═══════════╪════════════╡
│ 2025-01-03 ┆ AXAEDII FP Equity ┆ 567.18  ┆ -0.001074 ┆ 2024-12-31 │
│ 2025-01-10 ┆ AXAEDII FP Equity ┆ 549.48  ┆ -0.031207 ┆ 2025-01-03 │
│ 2025-01-17 ┆ AXAEDII FP Equity ┆ 570.79  ┆ 0.038782  ┆ 2025-01-10 │
│ 2025-01-24 ┆ AXAEDII FP Equity ┆ 564.71  ┆ -0.010652 ┆ 2025-01-17 │
│ 2025-01-31 ┆ AXAEDII FP Equity ┆ 592.1   ┆ 0.048503  ┆ 2025-01-24 │
│ …          ┆ …                 ┆ …       ┆ …         ┆ …          │
│ 2025-12-05 ┆ VANEINI ID Equity ┆ 37.1985 ┆ 0.004342  ┆ 2025-11-28 │
│ 2025-12-12 ┆ VANEINI ID Equity ┆ 37.1576 ┆ -0.0011   ┆ 2025-12-05 │
│ 2025-12-19 ┆ VANEINI ID Equity ┆ 37.8228 ┆ 0.017902  ┆ 2025-12-12 │
│ 2025-12-24 ┆ VANEINI ID Equity ┆ 37.8081 ┆ -0.000389 ┆ 2025-12-19 │
│ 2025-12-31 ┆ VANEINI ID Equity ┆ 38.03   ┆ 0.005869  ┆ 2025-12-24 │
└────────────┴───────────────────┴─────────┴───────────┴────────────┘

In [91]:
# Poids de chaque fonds par date VL : w_i,t = VB_i,t / Σ_j VB_j,t

df_total = df_vb.group_by("Date").agg(pl.col("VB").sum().alias("VB_total"))

df_weights = (
    df_vb.join(df_total, on="Date")
    .join(df_meta.select(["ISIN", "Code Bloomberg"]), on="ISIN")
    .with_columns((pl.col("VB") / pl.col("VB_total")).alias("weight"))
    .select(["Date", "Code Bloomberg", "weight"])
)

df_weights

shape: (1_562, 3)
┌────────────┬───────────────────┬──────────┐
│ Date       ┆ Code Bloomberg    ┆ weight   │
│ ---        ┆ ---               ┆ ---      │
│ date       ┆ str               ┆ f64      │
╞════════════╪═══════════════════╪══════════╡
│ 2024-12-06 ┆ AXAEDII FP Equity ┆ 0.023506 │
│ 2024-12-06 ┆ ODEUMCB FP Equity ┆ 0.019124 │
│ 2024-12-06 ┆ EMGACTD FP Equity ┆ 0.000092 │
│ 2024-12-06 ┆ EMAIIDC FP Equity ┆ 0.018609 │
│ 2024-12-06 ┆ BDLCONI FP Equity ┆ 0.030353 │
│ …          ┆ …                 ┆ …        │
│ 2025-12-31 ┆ EX2ESCS LX Equity ┆ 0.041425 │
│ 2025-12-31 ┆ CV9 FP Equity     ┆ 0.025406 │
│ 2025-12-31 ┆ CE2D LN Equity    ┆ 0.144467 │
│ 2025-12-31 ┆ MGSECIA LX Equity ┆ 0.046981 │
│ 2025-12-31 ┆ DNAMESE LX Equity ┆ 0.031932 │
└────────────┴───────────────────┴──────────┘

In [92]:
# Assemblage : (prev_date, Date, fonds, r_i, w_i, r_b, bench_ticker, r_bi) par periode

# Retour du benchmark de poche (r_B)
df_bench = (
    df_ret.filter(pl.col("Code Bloomberg") == BENCHMARK)
    .select(["prev_date", "Date", pl.col("r").alias("r_b")])
)

# Retours de tous les benchmarks de style (inclut BENCHMARK lui-meme)
df_style_ret = (
    df_ret.filter(pl.col("Code Bloomberg").is_in(STYLE_BENCHMARKS))
    .select(
        [
            "Date",
            pl.col("Code Bloomberg").alias("bench_ticker"),
            pl.col("r").alias("r_bi"),
        ]
    )
)

# Fonds (exclure tous les benchmarks)
df_funds = (
    df_ret.filter(~pl.col("Code Bloomberg").is_in(STYLE_BENCHMARKS))
    .rename({"r": "r_i"})
    .join(df_meta.select(["Code Bloomberg", "Instrument"]), on="Code Bloomberg")
    .with_columns(
        pl.col("Instrument")
        .map_elements(
            lambda n: FUND_BENCHMARK.get(n, BENCHMARK), return_dtype=pl.Utf8
        )
        .alias("bench_ticker")
    )
)

df_attr = (
    df_funds.join(
        df_weights,
        left_on=["prev_date", "Code Bloomberg"],
        right_on=["Date", "Code Bloomberg"],
        how="left",
    )
    .with_columns(pl.col("weight").fill_null(0.0))
    .join(df_bench.select(["prev_date", "r_b"]), on="prev_date")
    .join(df_style_ret, on=["Date", "bench_ticker"], how="left")
)

# Sanity : fonds sans r_bi (benchmark manquant ?)
unmatched = df_attr.filter(pl.col("r_bi").is_null())["Instrument"].unique().to_list()
if unmatched:
    print(f"WARNING : r_bi manquant pour : {unmatched}")

df_attr

shape: (1_485, 10)
┌────────────┬─────────────┬─────────┬───────────┬───┬────────────┬──────────┬──────────┬──────────┐
│ Date       ┆ Code        ┆ TRI     ┆ r_i       ┆ … ┆ bench_tick ┆ weight   ┆ r_b      ┆ r_bi     │
│ ---        ┆ Bloomberg   ┆ ---     ┆ ---       ┆   ┆ er         ┆ ---      ┆ ---      ┆ ---      │
│ date       ┆ ---         ┆ f64     ┆ f64       ┆   ┆ ---        ┆ f64      ┆ f64      ┆ f64      │
│            ┆ str         ┆         ┆           ┆   ┆ str        ┆          ┆          ┆          │
╞════════════╪═════════════╪═════════╪═══════════╪═══╪════════════╪══════════╪══════════╪══════════╡
│ 2025-01-03 ┆ AXAEDII FP  ┆ 567.18  ┆ -0.001074 ┆ … ┆ M7EU000V   ┆ 0.022997 ┆ 0.001399 ┆ 0.002521 │
│            ┆ Equity      ┆         ┆           ┆   ┆ Index      ┆          ┆          ┆          │
│ 2025-01-10 ┆ AXAEDII FP  ┆ 549.48  ┆ -0.031207 ┆ … ┆ M7EU000V   ┆ 0.022904 ┆ 0.007965 ┆ 0.001863 │
│            ┆ Equity      ┆         ┆           ┆   ┆ Index      ┆          ┆          ┆          │
│ 2025-01-17 ┆ AXAEDII FP  ┆ 570.79  ┆ 0.038782  ┆ … ┆ M7EU000V   ┆ 0.022347 ┆ 0.023558 ┆ 0.027707 │
│            ┆ Equity      ┆         ┆           ┆   ┆ Index      ┆          ┆          ┆          │
│ 2025-01-24 ┆ AXAEDII FP  ┆ 564.71  ┆ -0.010652 ┆ … ┆ M7EU000V   ┆ 0.022412 ┆ 0.0123   ┆ 0.005127 │
│            ┆ Equity      ┆         ┆           ┆   ┆ Index      ┆          ┆          ┆          │
│ 2025-01-31 ┆ AXAEDII FP  ┆ 592.1   ┆ 0.048503  ┆ … ┆ M7EU000V   ┆ 0.021918 ┆ 0.018013 ┆ 0.024002 │
│            ┆ Equity      ┆         ┆           ┆   ┆ Index      ┆          ┆          ┆          │
│ …          ┆ …           ┆ …       ┆ …         ┆ … ┆ …          ┆ …        ┆ …        ┆ …        │
│ 2025-12-05 ┆ VANEINI ID  ┆ 37.1985 ┆ 0.004342  ┆ … ┆ M7EU Index ┆ 0.09792  ┆ 0.004274 ┆ 0.004274 │
│            ┆ Equity      ┆         ┆           ┆   ┆            ┆          ┆          ┆          │
│ 2025-12-12 ┆ VANEINI ID  ┆ 37.1576 ┆ -0.0011   ┆ … ┆ M7EU Index ┆ 0.098005 ┆ -0.00107 ┆ -0.00107 │
│            ┆ Equity      ┆         ┆           ┆   ┆            ┆          ┆          ┆          │
│ 2025-12-19 ┆ VANEINI ID  ┆ 37.8228 ┆ 0.017902  ┆ … ┆ M7EU Index ┆ 0.09828  ┆ 0.015664 ┆ 0.015664 │
│            ┆ Equity      ┆         ┆           ┆   ┆            ┆          ┆          ┆          │
│ 2025-12-24 ┆ VANEINI ID  ┆ 37.8081 ┆ -0.000389 ┆ … ┆ M7EU Index ┆ 0.098619 ┆ 0.001834 ┆ 0.001834 │
│            ┆ Equity      ┆         ┆           ┆   ┆            ┆          ┆          ┆          │
│ 2025-12-31 ┆ VANEINI ID  ┆ 38.03   ┆ 0.005869  ┆ … ┆ M7EU Index ┆ 0.093925 ┆ 0.005792 ┆ 0.005792 │
│            ┆ Equity      ┆         ┆           ┆   ┆            ┆          ┆          ┆          │
└────────────┴─────────────┴─────────┴───────────┴───┴────────────┴──────────┴──────────┴──────────┘

In [93]:
# Retour portefeuille par periode (r_p = Σ_i w_i * r_i) et chainage annuel
df_port = (
    df_attr.group_by(["prev_date", "Date"])
    .agg((pl.col("weight") * pl.col("r_i")).sum().alias("r_p"))
    .join(df_bench.select(["Date", "r_b"]), on="Date")
    .sort("Date")
)

R_P = float((1 + df_port["r_p"]).product() - 1)
R_B = float((1 + df_port["r_b"]).product() - 1)
print(f"R_P = {R_P:.4%}   R_B = {R_B:.4%}   Excess = {R_P - R_B:.4%}")
df_port

R_P = 18.0505%   R_B = 19.3863%   Excess = -1.3358%

shape: (55, 4)
┌────────────┬────────────┬───────────┬──────────┐
│ prev_date  ┆ Date       ┆ r_p       ┆ r_b      │
│ ---        ┆ ---        ┆ ---       ┆ ---      │
│ date       ┆ date       ┆ f64       ┆ f64      │
╞════════════╪════════════╪═══════════╪══════════╡
│ 2024-12-31 ┆ 2025-01-03 ┆ 0.001785  ┆ 0.001399 │
│ 2025-01-03 ┆ 2025-01-10 ┆ 0.005052  ┆ 0.007965 │
│ 2025-01-10 ┆ 2025-01-17 ┆ 0.022254  ┆ 0.023558 │
│ 2025-01-17 ┆ 2025-01-24 ┆ 0.012045  ┆ 0.0123   │
│ 2025-01-24 ┆ 2025-01-31 ┆ 0.019225  ┆ 0.018013 │
│ …          ┆ …          ┆ …         ┆ …        │
│ 2025-11-28 ┆ 2025-12-05 ┆ 0.003438  ┆ 0.004274 │
│ 2025-12-05 ┆ 2025-12-12 ┆ -0.000451 ┆ -0.00107 │
│ 2025-12-12 ┆ 2025-12-19 ┆ 0.014903  ┆ 0.015664 │
│ 2025-12-19 ┆ 2025-12-24 ┆ 0.001053  ┆ 0.001834 │
│ 2025-12-24 ┆ 2025-12-31 ┆ 0.00697   ┆ 0.005792 │
└────────────┴────────────┴───────────┴──────────┘

In [94]:
# Decomposition Brinson (simplifiee) + lissage Carino
# Par periode :
#   allocation_i,t = (k_t/K) * w_i,t * (r_bi,t - r_B,t)     <- choix de style
#   selection_i,t  = (k_t/K) * w_i,t * (r_i,t  - r_bi,t)    <- choix de fonds
#   contribution_i,t = allocation_i,t + selection_i,t = (k_t/K) * w_i,t * (r_i,t - r_B,t)


def carino_k(rp: np.ndarray, rb: np.ndarray) -> np.ndarray:
    same = np.isclose(rp, rb)
    safe_diff = np.where(same, 1.0, rp - rb)
    return np.where(
        same,
        1.0 / (1.0 + rp),
        (np.log1p(rp) - np.log1p(rb)) / safe_diff,
    )


if np.isclose(R_P, R_B):
    K = 1.0 / (1.0 + R_P)
else:
    K = (np.log1p(R_P) - np.log1p(R_B)) / (R_P - R_B)

df_port = df_port.with_columns(
    pl.Series("k_t", carino_k(df_port["r_p"].to_numpy(), df_port["r_b"].to_numpy()))
)

df_attr2 = df_attr.join(df_port.select(["Date", "k_t"]), on="Date").with_columns(
    [
        (pl.col("k_t") / K * pl.col("weight") * (pl.col("r_bi") - pl.col("r_b")))
        .alias("allocation"),
        (pl.col("k_t") / K * pl.col("weight") * (pl.col("r_i") - pl.col("r_bi")))
        .alias("selection"),
        (pl.col("k_t") / K * pl.col("weight") * (pl.col("r_i") - pl.col("r_b")))
        .alias("contrib_carino"),
    ]
)

df_perf_fund = (
    df_funds.group_by("Code Bloomberg")
    .agg(((1 + pl.col("r_i")).product() - 1).alias("perf_cum"))
)

df_poids_moyen = (
    df_attr.group_by("Code Bloomberg")
    .agg(pl.col("weight").mean().alias("weight_avg"))
)

df_bench_map = (
    df_funds.select(["Code Bloomberg", "bench_ticker"]).unique()
)

df_contrib = (
    df_attr2.group_by("Code Bloomberg")
    .agg(
        [
            pl.col("allocation").sum(),
            pl.col("selection").sum(),
            pl.col("contrib_carino").sum(),
        ]
    )
    .join(df_perf_fund, on="Code Bloomberg")
    .join(df_poids_moyen, on="Code Bloomberg")
    .join(df_bench_map, on="Code Bloomberg")
    .join(df_meta.select(["Code Bloomberg", "Instrument"]), on="Code Bloomberg")
    .with_columns((pl.col("perf_cum") - R_B).alias("perf_relative"))
    .sort("contrib_carino", descending=True)
)

print(
    f"Σ allocation = {df_contrib['allocation'].sum():.4%}   "
    f"Σ selection = {df_contrib['selection'].sum():.4%}   "
    f"Σ contribution = {df_contrib['contrib_carino'].sum():.4%}   "
    f"vs Excess = {R_P - R_B:.4%}"
)
df_contrib

Σ allocation = 0.6584%   Σ selection = -1.6960%   Σ contribution = -1.0376%   vs Excess = -1.3358%

shape: (27, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Code      ┆ allocatio ┆ selection ┆ contrib_c ┆ … ┆ weight_av ┆ bench_tic ┆ Instrumen ┆ perf_rel │
│ Bloomberg ┆ n         ┆ ---       ┆ arino     ┆   ┆ g         ┆ ker       ┆ t         ┆ ative    │
│ ---       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆ str       ┆ str       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ STZ FP    ┆ 0.0       ┆ 0.011171  ┆ 0.011171  ┆ … ┆ 0.044396  ┆ M7EU      ┆ ETF SPDR  ┆ 0.274115 │
│ Equity    ┆           ┆           ┆           ┆   ┆           ┆ Index     ┆ MSCI      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EUROP     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ FINANC    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ UCI…      ┆          │
│ MGSECIA   ┆ 0.004407  ┆ 0.000667  ┆ 0.005073  ┆ … ┆ 0.040098  ┆ M7EU000V  ┆ M&G       ┆ 0.136227 │
│ LX Equity ┆           ┆           ┆           ┆   ┆           ┆ Index     ┆ EUROPEAN  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ STGIC     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ VALUE EUR ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ C…        ┆          │
│ CV9 FP    ┆ 0.002393  ┆ 0.000041  ┆ 0.002434  ┆ … ┆ 0.021793  ┆ M7EU000V  ┆ ETF       ┆ 0.113443 │
│ Equity    ┆           ┆           ┆           ┆   ┆           ┆ Index     ┆ AMUNDI    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ MSCI      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EUROPE    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ VALUE F…  ┆          │
│ IEVL.LN   ┆ 0.001091  ┆ 0.000439  ┆ 0.00153   ┆ … ┆ 0.014025  ┆ M7EU000V  ┆ ETF       ┆ 0.165338 │
│ Equity    ┆           ┆           ┆           ┆   ┆           ┆ Index     ┆ ISHARES   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EUROPE    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ VALUE     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ FACTO…    ┆          │
│ IMEU LN   ┆ 0.0       ┆ 0.001438  ┆ 0.001438  ┆ … ┆ 0.176734  ┆ M7EU      ┆ ETF       ┆ 0.008232 │
│ Equity    ┆           ┆           ┆           ┆   ┆           ┆ Index     ┆ ISHARES   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CORE MSCI ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EUROPE G… ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ EAMEIXL   ┆ -8.5582e- ┆ -0.003802 ┆ -0.003802 ┆ … ┆ 0.023844  ┆ M7EUSM    ┆ ECHIQ     ┆ -0.14332 │
│ FP Equity ┆ 7         ┆           ┆           ┆   ┆           ┆ Index     ┆ AGENOR    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ IXL EUR   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ NH        ┆          │
│ AXAEDII   ┆ 0.002182  ┆ -0.006113 ┆ -0.003931 ┆ … ┆ 0.01864   ┆ M7EU000V  ┆ AXA AEDIF ┆ -0.10724 │
│ FP Equity ┆           ┆           ┆           ┆   ┆           ┆ Index     ┆ ICANDI    ┆ 7        │
│ COMEEIA   ┆ -0.002506 ┆ -0.003483 ┆ -0.005989 ┆ … ┆ 0.021323  ┆ M7EU000G  ┆ COMGEST   ┆ -0.25308 │
│ ID Equity ┆           ┆           ┆           ┆   ┆           ┆ Index     ┆ GROWTH    ┆ 5        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EUROPE    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EUR I AC… ┆          │
│ EMAIIDC   ┆ 0.0       ┆ -0.006577 ┆ -0.006577 ┆ … ┆ 0.013205  ┆ M7EU      ┆ EMERGENCE ┆ -0.42922 │
│ FP Equity ┆           ┆           ┆           ┆   ┆           ┆ Index     ┆ ACT 2     ┆ 1        │
│ CEEUREA   ┆ -0.0029   ┆ -0.004407 ┆ -0.007307 ┆ … ┆ 0.025377  ┆ M7EU000G  ┆ COMGEST   ┆ -0.26438 │
│ ID Equity ┆           ┆           ┆           ┆   ┆           ┆ Index     ┆ EUROPE    ┆ 8        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ COMP EUR  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EA ACC    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# --- Diagnostic : d'ou vient l'ecart (Σ contrib − (R_P − R_B)) ?

# Somme des poids matches par periode (Σ_i w_i,t dans df_attr)
df_W = (
    df_attr.group_by(["prev_date", "Date"])
    .agg(pl.col("weight").sum().alias("W_t"))
    .join(df_port.select(["Date", "r_p", "r_b", "k_t"]), on="Date")
    .sort("Date")
)

print("Poids matches par periode (sample) :")
print(df_W.head(10))
print(f"\nW_t moyen : {df_W['W_t'].mean():.4%}")
print(f"W_t min   : {df_W['W_t'].min():.4%}")

# Biais theorique = Σ_t (k_t/K) * r_b,t * (1 - W_t)
biais_theo = float(
    ((df_W["k_t"] / K) * df_W["r_b"] * (1 - df_W["W_t"])).sum()
)
ecart_obs = float(df_contrib["contrib_carino"].sum()) - (R_P - R_B)

print(f"\nEcart observe       Σ contrib − (R_P − R_B) = {ecart_obs:.4%}")
print(f"Biais predit par (1) Σ(k_t/K)·r_b·(1−W_t)    = {biais_theo:.4%}")
print(f"Residuel (source 2 : drop_nulls)             = {ecart_obs - biais_theo:.4%}")


# --- Verification : renormaliser les poids au perimetre matche
# W_t = Σ_matched w_i -> on divise par W_t pour avoir des poids qui somment a 1
df_attr_norm = (
    df_attr.join(df_W.select(["Date", "W_t"]), on="Date")
    .with_columns((pl.col("weight") / pl.col("W_t")).alias("weight"))
)

df_port_norm = (
    df_attr_norm.group_by(["prev_date", "Date"])
    .agg((pl.col("weight") * pl.col("r_i")).sum().alias("r_p"))
    .join(df_bench.select(["Date", "r_b"]), on="Date")
    .sort("Date")
)

R_P_norm = float((1 + df_port_norm["r_p"]).product() - 1)
R_B_norm = float((1 + df_port_norm["r_b"]).product() - 1)

if np.isclose(R_P_norm, R_B_norm):
    K_norm = 1.0 / (1.0 + R_P_norm)
else:
    K_norm = (np.log1p(R_P_norm) - np.log1p(R_B_norm)) / (R_P_norm - R_B_norm)

df_port_norm = df_port_norm.with_columns(
    pl.Series(
        "k_t",
        carino_k(df_port_norm["r_p"].to_numpy(), df_port_norm["r_b"].to_numpy()),
    )
)

contrib_sum_norm = float(
    (
        df_attr_norm.join(df_port_norm.select(["Date", "k_t"]), on="Date")
        .with_columns(
            (
                pl.col("k_t")
                / K_norm
                * pl.col("weight")
                * (pl.col("r_i") - pl.col("r_b"))
            ).alias("c")
        )["c"]
    ).sum()
)

print("\n--- Apres renormalisation des poids ---")
print(f"R_P_norm = {R_P_norm:.4%}   R_B = {R_B_norm:.4%}   Excess = {R_P_norm - R_B_norm:.4%}")
print(f"Σ contrib_norm = {contrib_sum_norm:.4%}")
print(f"Residuel final = {contrib_sum_norm - (R_P_norm - R_B_norm):.6%}")

In [95]:
# Tableau de restitution

table = (
    GT(
        df_contrib.select(
            [
                "Instrument",
                "bench_ticker",
                "weight_avg",
                "perf_cum",
                "perf_relative",
                "allocation",
                "selection",
                "contrib_carino",
            ]
        )
    )
    .tab_header(
        title=md("Attribution de performance relative 2025 — Poche Europe"),
        subtitle=md(
            f"vs {BENCHMARK} · R_P = {R_P:.2%} · R_B = {R_B:.2%} · "
            f"Excess = {R_P - R_B:.2%}"
        ),
    )
    .fmt_percent(
        columns=[
            "weight_avg",
            "perf_cum",
            "perf_relative",
            "allocation",
            "selection",
            "contrib_carino",
        ],
        decimals=2,
    )
    .cols_label(
        bench_ticker="Benchmark",
        weight_avg="Poids moyen",
        perf_cum="Perf. cumulée",
        perf_relative="Perf. relative",
        allocation="Allocation",
        selection="Sélection",
        contrib_carino="Contribution totale",
    )
    .opt_stylize(style=6, color="blue")
)
table

GT(_tbl_data=shape: (27, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ Instrument ┆ bench_tick ┆ weight_avg ┆ perf_cum  ┆ perf_rela ┆ allocatio ┆ selection ┆ contrib_c │
│ ---        ┆ er         ┆ ---        ┆ ---       ┆ tive      ┆ n         ┆ ---       ┆ arino     │
│ str        ┆ ---        ┆ f64        ┆ f64       ┆ ---       ┆ ---       ┆ f64       ┆ ---       │
│            ┆ str        ┆            ┆           ┆ f64       ┆ f64       ┆           ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ETF SPDR   ┆ M7EU Index ┆ 0.044396   ┆ 0.467978  ┆ 0.274115  ┆ 0.0       ┆ 0.011171  ┆ 0.011171  │
│ MSCI EUROP ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ FINANC     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ UCI…       ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ M&G        ┆ M7EU000V   ┆ 0.040098   ┆ 0.33009   ┆ 0.136227  ┆ 0.004407  ┆ 0.000667  ┆ 0.005073  │
│ EUROPEAN   ┆ Index      ┆            ┆           ┆           ┆           ┆           ┆           │
│ STGIC      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ VALUE EUR  ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ C…         ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ETF AMUNDI ┆ M7EU000V   ┆ 0.021793   ┆ 0.307306  ┆ 0.113443  ┆ 0.002393  ┆ 0.000041  ┆ 0.002434  │
│ MSCI       ┆ Index      ┆            ┆           ┆           ┆           ┆           ┆           │
│ EUROPE     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ VALUE F…   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ETF        ┆ M7EU000V   ┆ 0.014025   ┆ 0.359201  ┆ 0.165338  ┆ 0.001091  ┆ 0.000439  ┆ 0.00153   │
│ ISHARES    ┆ Index      ┆            ┆           ┆           ┆           ┆           ┆           │
│ EUROPE     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ VALUE      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ FACTO…     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ETF        ┆ M7EU Index ┆ 0.176734   ┆ 0.202096  ┆ 0.008232  ┆ 0.0       ┆ 0.001438  ┆ 0.001438  │
│ ISHARES    ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ CORE MSCI  ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ EUROPE G…  ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ ECHIQ      ┆ M7EUSM     ┆ 0.023844   ┆ 0.050543  ┆ -0.14332  ┆ -8.5582e- ┆ -0.003802 ┆ -0.003802 │
│ AGENOR IXL ┆ Index      ┆            ┆           ┆           ┆ 7         ┆           ┆           │
│ EUR NH     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ AXA AEDIFI ┆ M7EU000V   ┆ 0.01864    ┆ 0.086617  ┆ -0.107247 ┆ 0.002182  ┆ -0.006113 ┆ -0.003931 │
│ CANDI      ┆ Index      ┆            ┆           ┆           ┆           ┆           ┆           │
│ COMGEST    ┆ M7EU000G   ┆ 0.021323   ┆ -0.059222 ┆ -0.253085 ┆ -0.002506 ┆ -0.003483 ┆ -0.005989 │
│ GROWTH     ┆ Index      ┆            ┆           ┆           ┆           ┆           ┆           │
│ EUROPE EUR ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ I AC…      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ EMERGENCE  ┆ M7EU Index ┆ 0.013205   ┆ -0.235357 ┆ -0.429221 ┆ 0.0       ┆ -0.006577 ┆ -0.006577 │
│ ACT 2      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ COMGEST    ┆ M7EU000G   ┆ 0.025377   ┆ -0.070524 ┆ -0.264388 ┆ -0.0029   ┆ -0.004407 ┆ -0.007307 │
│ EUROPE     ┆ Index      ┆            ┆           ┆           ┆           ┆           ┆           │
│ COMP EUR   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ EA ACC     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │